scrape_configs:
  - job_name: 'spring-boot-app'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 3s
    static_configs:
      - targets: ['backend:8080']
  
  - job_name: 'kafka-exporter'
    metrics_path: '/metrics'
    scrape_interval: 3s
    static_configs:
      - targets: ['monitoring-broker:9308']

  - job_name: redis_exporter
    metrics_path: '/metrics'
    scrape_interval: 3s
    static_configs:
    - targets: ['monitoring-cache:9121']

  - job_name: 'kafka-jmx'
    static_configs:
      - targets: ['kafka:7071']
