spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: worker-group

app:
  kafka:
    topics: 
      jobs: jobs
      logs: logs
  logger:
    batch-size: 20
    flush-interval-ms: 2000
    use-formatter: true
