spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: worker-group
      enable-auto-commit: false   # Temporary

logging:
  level:
    org.eduscript.services.impl: DEBUG
    # org.springframework.cache.*: trace
    
app:
  k8s:
    namespace: default
    master-url: https://127.0.0.1:45255
    trust-certs: true
  kafka:
    topics: 
      jobs: jobs
      logs: logs
  logger:
    batch-size: 12
    flush-interval-ms: 3000
    use-formatter: true
