spring:
  data:
    redis:
      host: localhost
      port: 6379
    
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: backend-group

springdoc:
  api-docs:
    path: /api-docs
  show-actuator: true
  cache:
    disabled: true
  swagger-ui:
    doc-expansion: none
    operations-sorter: alpha
    tags-sorter: alpha

app:
  constants:
    user-id-attribute: userId
  kafka:
    topics: 
      jobs: jobs
      logs: logs
