grpc:
  client:
    GLOBAL:
      negotiation-type: plaintext  # TODO: add this in dev
    __name__:
      negotiationType: plaintext
  server:
    port: 9090

spring:
  data:
    redis:
      # host: cache
      port: 6379
    
  kafka:
    bootstrap-servers: localhost:9092
    # bootstrap-servers: broker:29092
    consumer:
      group-id: backend-group

app:
  constants:
    user-id-attribute: userId
  kafka:
    topics: 
      jobs: jobs
      logs: logs
