spring:
  grpc:
    server:
      port: 9090
      reflection:
        enabled: true
  data:
    redis:
      host: localhost
      port: 6379
    
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: backend-group

app:
  constants:
    user-id-attribute: userId
  kafka:
    topics: 
      jobs: jobs
      logs: logs
