spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: backend-group

springdoc:
  api-docs:
    path: /api-docs
  show-actuator: true
  cache:
    disabled: true
  swagger-ui:
    doc-expansion: none
    operations-sorter: alpha
    tags-sorter: alpha

app:
  kafka:
    topics: 
      jobs: jobs
