grpc:
  client:
    GLOBAL:
      negotiation-type: plaintext  # dev
    __name__:
      negotiationType: plaintext  # dev
  server:
    port: 50051
    health-service:
      type: ACTUATOR

management:
  endpoint:
    health:
      show-details: always  # dev
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include:
          - health
          - prometheus


spring:
  data:
    redis:
      # host: cache
      port: 6379
    
  kafka:
    bootstrap-servers: localhost:9092
    # bootstrap-servers: broker:29092
    consumer:
      group-id: backend-group

app:
  constants:
    user-id-attribute: userId
  kafka:
    topics: 
      jobs: jobs
      logs: logs
