services:
  code-server:
    build: .
    ports:
      - "8443:8443"
      - "8080:8080"
    volumes:
      - ./eduscript-extension:/home/coder/extensions
      - coder-data:/home/coder/project
    environment:
      - PASSWORD=eduscript123

volumes:
  coder-data:
